name: Dependency Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          RENOVATE_REPOSITORIES: "jwbennet/.github"
